### ISSUE TITLE
Crash Report: Input Offsets Crashes the game

### ISSUE THREAD

**Issue by Honton129** [Denoohay/spooky-mix-source#1]
### Issue Checklist

- [X] I have properly named my issue
- [X] I have checked the Issues/Discussions pages to see if my issue has already been reported

### Platform

Itch.io (Downloadable Build) - Windows

### Browser

None

### Version

1.0.0 - 1.0.1

### Description

The title is self-explainatory but yeah, it crashes when you try to adjust the offsets.
(On 1.0.0, it crashes also when trying to leave)
it doesn't returns a crash log and only pop ups the 'Null Object Reference' error.
![image](https://github.com/user-attachments/assets/f7bca9a7-e316-4bbd-9e48-e41caca0fe31)

### Steps to Reproduce

1. Go to Input Offsets at Options
2. Press Left, Right, Up or Down to change the offsets
3. Crash Appears
4. Depression :(

### Crash logs

[crash-2024-11-06-20-56-49.log](https://github.com/user-attachments/files/17692773/crash-2024-11-06-20-56-49.log)
This crash log is not at all related but in 1.0.0, trying to leave the menu crashed the game.
The current issue doesn't returns a crash log...

**Comment by Denoohay** [comment]
Issue has been resolved. A fix for this will be included in v1.0.2.

**Comment by Denoohay** [comment]
Issue has been resolved. A fix for this will be included in v1.0.2.
